tasks: $tasks
init:
  db3Secrets: ${secrets.$mysqlCredentials}
pipeline:
  destroy:
    stop-images:
      action: docker:stop
      images:
      - aerospike
      - mysql
  init:

    services:


      aerospike:
        action: docker:run
        image: 'aerospike/aerospike-server:3.16.0.6'
        name: endly_db1
        ports:
          3000: 3000
          3001: 3001
          3002: 3002
          3003: 3003
          8081: 8081

      aerospike-ip:
        action: docker:inspect
        logging: false
        name: endly_db1
        post:
        - dbIP = $Info[0].NetworkSettings.IPAddress
        - aerospikeIP = $Info[0].NetworkSettings.IPAddress

      mysql:
        action: docker:run
        image: mysql:5.7
        name: endly_db3
        ports:
          3306: 3306
        env:
          MYSQL_ROOT_PASSWORD: ${db3Secrets.Password}

      mysql-ip:
        action: docker:inspect
        logging: false
        name: endly_db3
        post:
        - dbIP = $Info[0].NetworkSettings.IPAddress
        - mysqlIP = $Info[0].NetworkSettings.IPAddress
