pipeline:
  db1:
    register:
      action: dsunit:register
      datastore: db1
      config:
        driverName: aerospike
        descriptor: tcp([host]:3000)/[namespace]
        parameters:
          dbname: db1
          namespace: test
          host: 127.0.0.1
          port: 3000
          dateFormat: yyyy-MM-dd hh:mm:ss
    prepare:
      data:
        action: nop
        init:
        - db1key = data.db1.setup
        - db1Setup = $AsTableRecords($db1key)
      setup:
        datastore: db1
        action: dsunit:prepare
        URL: regression/db1/data/
        data: $db1Setup
  db2:
    register:
      action: dsunit:register
      datastore: db2
      config:
        driverName: bigquery
        credentials: $bqCredentials
        parameters:
          datasetId: db2
    prepare:
      sequence:
        datastore: db2
        action: dsunit.sequence
        tables:
        - dummy
        - dummy_type
        post:
        - seq = $Sequences
      data:
        action: nop
        init:
        - db2key = data.db2.setup
        - db2Setup = $AsTableRecords($db2key)
      setup:
        datastore: db2
        action: dsunit:prepare
        URL: regression/db2/data/
        data: $db2Setup
  db3:
    register:
      action: dsunit:register
      datastore: db3
      config:
        driverName: mysql
        descriptor: '[username]:[password]@tcp(127.0.0.1:3306)/[dbname]?parseTime=true'
        credentials: $mysqlCredentials
        parameters:
          dbname: db3
    prepare:
      sequence:
        datastore: db3
        action: dsunit.sequence
        tables:
        - dummy
        - dummy_type
        post:
        - seq = $Sequences
      data:
        action: nop
        init:
        - db3key = data.db3.setup
        - db3Setup = $AsTableRecords($db3key)
      setup:
        datastore: db3
        action: dsunit:prepare
        URL: regression/db3/data/
        data: $db3Setup
