pipeline:
  db1:
    aerospike-ip:
      action: docker:inspect
      target: $target
      name: endly_db1
      post:
      - dbIP = $Info[0].NetworkSettings.IPAddress
      - aerospikeIP = $Info[0].NetworkSettings.IPAddress
    register:
      action: dsunit:register
      datastore: db1
      config:
        driverName: aerospike
        descriptor: tcp([host]:3000)/[namespace]
        parameters:
          dbname: db1
          namespace: test
          host: 127.0.0.1
          port: 3000
          dateFormat: yyyy-MM-dd hh:mm:ss
  db2:
    register:
      action: dsunit:register
      datastore: db2
      config:
        driverName: bigquery
        credentials: $bqCredentials
        parameters:
          datasetId: db2
  db3:
    mysql-ip:
      action: docker:inspect
      target: $target
      name: endly_db3
      post:
      - dbIP = $Info[0].NetworkSettings.IPAddress
      - mysqlIP = $Info[0].NetworkSettings.IPAddress
    register:
      action: dsunit:register
      datastore: db3
      config:
        driverName: mysql
        descriptor: '[username]:[password]@tcp(127.0.0.1:3306)/[dbname]?parseTime=true'
        credentials: $mysqlCredentials
        parameters:
          dbname: db3
